
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mydea_sample
  pool: 5
  username: root
  password:
  host: localhost


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mydea_sample
  pool: 5
  username: root
  password:
  host: localhost
